### ISSUE TITLE
max brightness on reboot

### ISSUE THREAD

**Issue by eiiiiix** [devnoname120/vitabright#4] opened 2018-03-14 17:58 UTC
when ever i reboot or unlock the screen brightness goes to maximum but is still shown in minimum spot

**Comment by devnoname120** [comment] 2018-04-06 15:31
Duplicate of https://github.com/devnoname120/vitabright/issues/3.

**Closed** 2018-04-06 15:31 UTC
Labels: duplicate

**Comment by eiiiiix** [comment] 2018-04-15 21:09
rip
thanks for the update though!
